version: '3'

services:
  frontend:
    build: frontend
    environment:
      ENDPOINT: ${ENPOINT}
    command: npm run build
    volumes:
      - frontend_build:/usr/src/app/build

  nginx:
    image: nginx
    volumes:
      - frontend_build:/usr/share/nginx/html
    ports:
      - 80:80

volumes:
  frontend_build: