version: '3'

services:
  frontend:
    build: frontend
    volumes:
      - ./frontend/src:/usr/src/app/src
    ports:
      - 8000:8000

  db:
    environment:
      POSTGRES_DB: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_USER: demo
    image: postgres:9.4
    volumes:
      - dbdata:/var/lib/postgresql/data

  backend:
    build: backend
    command: ../wait-for db:5432 -- go run main.go
    environment:
      DATABASE_URL: postgres://demo:demo@db/demo
    ports:
      - 9000:8080
    volumes:
    - ./backend/cmd:/go/src/app/cmd
    - ./backend/data:/go/src/app/data
    - ./backend/models:/go/src/app/models
    depends_on:
      - db
volumes:
  dbdata: